<meta charset="utf-8">
<?php 
	include 'core/core.php';
	


 
		$test = 	
		'<option value="32">آب نما آبشار آکواریوم</option>
			<option value="204">آبکاری(طلا-نیکل-کروم و غیره )</option>
			<option value="34">آتلیه عکاسی و فیلمبرداری</option>
			<option value="35">آرایشگاه آقایان</option>
			<option value="36">آرایشگاه بانوان</option>
			<option value="152">آرایشی و بهداشتی</option>
			<option value="37">آزمایشگاه تشخیص طبی</option>
			<option value="40">آژانس مسافرتی</option>
			<option value="39">آژانس مشاورین مسکن</option>
			<option value="38">آژانس-باربری-پیک موتوری حمل ونقل</option>
			<option value="193">آسانسور-بالابر</option>
			<option value="52">آسایشگاه سالمندان</option>
			<option value="33">آلات موسیقی خدمات و قطعات</option>
			<option value="51">آلبوم عکس</option>
			<option value="117">آلومینیوم(درب و پنجره)</option>
			<option value="270">آمبولانس(خصوصی-دولتی)</option>
			<option value="31">آموزشگاه و موسسات آموزشی</option>
			<option value="30">آهن آلات- فروش(همه نوع)</option>
			<option value="110">آهنگری وسازه های فلزی</option>
			<option value="45">ابزار آلات صنعتی(فروش-تعمیرات)</option>
			<option value="203">ابزارآلات(ساختمانی-یراق) </option>
			<option value="53">اتوماسیون و لوازم اندازه گیری</option>
			<option value="46">اتومبیل خرید-فروش</option>
			<option value="80">اتومبیل(خدمات)</option>
			<option value="230">اسانس و رنگ خوراکی</option>
			<option value="44">اسباب بازی</option>
			<option value="43">اغذیه -رستوران</option>
			<option value="42">الکتروموتور صنعتی و پمپ</option>
			<option value="215">الکترونیک(خدمات)</option>
			<option value="81">الکتریکی(لوازم و خدمات)</option>
			<option value="47">انبار کالا</option>
			<option value="41">انتشارات</option>
			<option value="184">اکو-آمپلی فایر(نور-صدا-تصویر)</option>
			<option value="54">باشگاه ورزشی و استخر</option>
			<option value="213">باطری(خانگی- صنعتی - اتومبیل )</option>
			<option value="55">بانکها و موسسات مالی</option>
			<option value="56">برشکاری و خمکاری</option>
			<option value="59">برق صنعتی</option>
			<option value="122">بسته بندی(صنایع)</option>
			<option value="60">بلبرینگ</option>
			<option value="57">بلور-کریستال-چینی</option>
			<option value="212">بیمارستان</option>
			<option value="58">بیمه</option>
			<option value="62">پارچه فروشی</option>
			<option value="66">پاکت و جعبه سازی</option>
			<option value="67">پرچم فروشی</option>
			<option value="63">پرده سرا</option>
			<option value="64">پرنده فروشی</option>
			<option value="82">پزشکی</option>
			<option value="166">پزشکی(لوازم )</option>
			<option value="125">پلاستیک -نایلون- ظروف یکبار مصرف و پلاسکو</option>
			<option value="178">پلاستیک(مواد اولیه )</option>
			<option value="248">پمپ بنزین </option>
			<option value="249">پمپ گاز</option>
			<option value="198">پمپ گاز و بنزین( ملزومات)</option>
			<option value="65">پوشاک(مردانه-زنانه -بچه گانه)</option>
			<option value="69">تابلو سازی-پارچه نویسی</option>
			<option value="70">تاسیسات و تهویه مطبوع ساختمان</option>
			<option value="68">تالار پذیرایی</option>
			<option value="71">تجهیزات آزمایشگاهی( فروش)</option>
			<option value="75">تجهیزات ایمنی کارمندی</option>
			<option value="72">تجهیزات صنعتی آشپزخانه</option>
			<option value="239">تجهیزات صنعتی و مهندسی</option>
			<option value="216">تجهیزات مخابراتی</option>
			<option value="258">تجهیزات هتل</option>
			<option value="209">ترازو-باسکول</option>
			<option value="73">تراشکاری</option>
			<option value="74">تزئینات داخلی ساختمان</option>
			<option value="238">تصفیه آب(فروش دستگاه - خدمات)</option>
			<option value="214">تلفن-گوشی(فروش-تعمیر)</option>
			<option value="267">تولیدی پوشاک-ماشین آلات و ملزومات</option>
			<option value="266">ثبت شرکت</option>
			<option value="76">جرثقیل و بالابرهای صنعتی</option>
			<option value="255">جوراب (مردانه-زنانه-بچه گانه)</option>
			<option value="77">جوشکاری-تعمیرات دستگاه جوش</option>
			<option value="83">چاپ و تبلیغات(خدمات-هدایای تبلیغاتی)</option>
			<option value="226">چاقو و قیچی سازی</option>
			<option value="79">چرخ خیاطی(فروش - تعمیر )</option>
			<option value="121">چرم(صنایع )</option>
			<option value="78">چسب صنعتی</option>
			<option value="118">چوب و فلز(صنایع )</option>
			<option value="84">خدمات ساختمانی</option>
			<option value="243">خدمات مجالس</option>
			<option value="156">خرازی</option>
			<option value="92">خشکبار-قنادی-لوازم قنادی</option>
			<option value="90">خشکشویی و لباسشویی</option>
			<option value="91">خیاطی-مزون-خرج کاری</option>
			<option value="93">خیمه-چادردوزی</option>
			<option value="97">دارالترجمه</option>
			<option value="246">داربست</option>
			<option value="95">داروخانه</option>
			<option value="94">داروهای گیاهی گیاهان دارویی(عطاری)</option>
			<option value="96">دامپزشکی(تجهیزات-دارو ولوازم )</option>
			<option value="98">دخانیات</option>
			<option value="210">درب و کرکره اتوماتیک</option>
			<option value="208">درمانگاه( کلینیک)</option>
			<option value="100">دفاتر ازدواج و طلاق</option>
			<option value="99">دفاتر اسناد رسمی</option>
			<option value="259">دفاتر پیشخوان دولت</option>
			<option value="101">دفتر خدماتی و امور مشترکین</option>
			<option value="245">دوربین عکاسی فیلمبرداری</option>
			<option value="195">دوربین مدار بسته</option>
			<option value="237">دکوراسیون داخلی-پارتیشن</option>
			<option value="105">رگال و مانکن</option>
			<option value="103">رنگهای ساختمانی-صنعتی-اتومبیل</option>
			<option value="200">ریخته گری</option>
			<option value="201">ریسندگی و بافندگی</option>
			<option value="104">رینگ و لاستیک اتومبیل</option>
			<option value="221">زنجیر-فولی</option>
			<option value="106">ساعت(فروش- تعمیر)</option>
			<option value="109">سراجی</option>
			<option value="107">سمساری</option>
			<option value="211">سنگ تزئینی طلا و جواهر</option>
			<option value="108">سنگ ساختمانی و سنگبری</option>
			<option value="224">سیستم برودتی</option>
			<option value="252">سیسمونی</option>
			<option value="113">شرکتهای خصوصی و دولتی</option>
			<option value="240">شلنگ فشارقوی-صنعتی</option>
			<option value="257">شمع روشنایی و پارافین صنعتی</option>
			<option value="115">شوینده و بهداشتی</option>
			<option value="232">شکار(لوازم)</option>
			<option value="114">شیشه و آیینه</option>
			<option value="227">صحافی</option>
			<option value="116">صرافی</option>
			<option value="119">صنایع دستی</option>
			<option value="85">صوتی و تصویری(خدمات)</option>
			<option value="123">صوتی-تصویری(فروش)</option>
			<option value="262">طب سوزنی و طب سنتی</option>
			<option value="217">طلا سازی-عیارسنجی و مخراجکاری</option>
			<option value="124">طلا و جواهر</option>
			<option value="207">طلق- توری-ورق </option>
			<option value="126">ظروف کرایه</option>
			<option value="225">عایق کاری</option>
			<option value="165">عکاسی و لوازم عکاسی</option>
			<option value="127">عینک(فروش و تعمیر)</option>
			<option value="128">فرآورده های پروتئینی</option>
			<option value="130">فرآورده های نسوز</option>
			<option value="256">فرش دست بافت</option>
			<option value="129">فرش ماشینی و موکت</option>
			<option value="206">فلزات رنگین</option>
			<option value="241">فنرسازی</option>
			<option value="242">فیلتر سازی(تولید و پخش)</option>
			<option value="131">قالبسازی و ریخته گری</option>
			<option value="132">قالیشویی-رفوگری</option>
			<option value="133">قطعات الکترونیکی</option>
			<option value="134">قطعات صنعتی</option>
			<option value="135">قطعات لاستیکی</option>
			<option value="268">قهوه(فروش)</option>
			<option value="149">گاوصندوق</option>
			<option value="191">گلدوزی</option>
			<option value="150">گلفروشی</option>
			<option value="189">گوناگون</option>
			<option value="151">گونی فروشی</option>
			<option value="253">لباس زیر(مردانه-زنانه-بچه گانه)</option>
			<option value="157">لوازم آشپزخانه</option>
			<option value="154">لوازم التحریر و ملزومات اداری</option>
			<option value="153">لوازم ایمنی - ترافیکی وآتش نشانی</option>
			<option value="167">لوازم تزئینی-دکوری خانگی</option>
			<option value="229">لوازم تزئینی-عروسی-تولد</option>
			<option value="87">لوازم خانگی(خدمات)</option>
			<option value="188">لوازم خانگی(فروش)</option>
			<option value="137">لوازم خانگی(قطعات یدکی)</option>
			<option value="254">لوازم گاز سوز خانگی</option>
			<option value="160">لوازم گازسوز اتومبیل</option>
			<option value="161">لوازم لوکس-ظبط وباند-شیشه اتومبیل</option>
			<option value="163">لوازم ورزشی و ملزومات استخر-سونا-جکوزی</option>
			<option value="192">لوازم کمک آموزشی و نقاشی</option>
			<option value="164">لوازم یدکی خودرو</option>
			<option value="162">لوازم یدکی ماشینهای راهسازی و سنگین</option>
			<option value="168">لوستر و آیینه شمعدان</option>
			<option value="155">لوله و اتصالات -لوازم بهداشتی ساختمان کاشی سرامیک </option>
			<option value="159">ماشین آلات کشاورزی</option>
			<option value="251">ماشین سازی(اتوماسیون و خط تولید)</option>
			<option value="175">ماشین های آلات سنگین و راهسازی</option>
			<option value="89">ماشین های اداری (فروش و خدمات)</option>
			<option value="261">ماشین و هواپیماهای رادیو کنترلی</option>
			<option value="250">مبلمان (لوازم و تعمیرات)</option>
			<option value="176">مبلمان و لوازم اداری</option>
			<option value="120">مبلمان(فروش)</option>
			<option value="170">محصولات فرهنگی و هنری</option>
			<option value="171">مصالح ساختمانی</option>
			<option value="202">مصنوعات پلاستیکی</option>
			<option value="265">مطب(پوست-مو-زیبایی)</option>
			<option value="260">ملزومات نظافتی و تجهیزات تعمیرگاهی</option>
			<option value="102">مهندسی نظارت(دفتر )</option>
			<option value="179">مواد شیمیایی و آزمایشگاهی</option>
			<option value="219">مواد محترقه(نور افشانی)</option>
			<option value="174">موادغذایی و سوپر مارکت</option>
			<option value="88">موبایل(خدمات و لوازم جانبی)</option>
			<option value="172">موتور سیکلت -دوچرخه</option>
			<option value="236">موسسات و انجمن های خیریه</option>
			<option value="173">میوه فروشی-سبزیجات</option>
			<option value="180">نانوایی سنتی و فانتزی</option>
			<option value="181">نجاری-منبت کاری</option>
			<option value="182">نخ و کاموا</option>
			<option value="183">نفت و گاز (تجهیزات)</option>
			<option value="185">نقاشی -خوشنویسی</option>
			<option value="218">نقره جات-زیور آلات</option>
			<option value="187">هتل </option>
			<option value="190">هیدرولیک-پنوماتیک-ابزار دقیق</option>
			<option value="186">وکلای دادگستری</option>
			<option value="112">کابینت(سیستم آشپزخانه)</option>
			<option value="197">کادویی(اجناس )</option>
			<option value="139">کارتن سازی</option>
			<option value="199">کارواش</option>
			<option value="269">کاشی سرامیک - چینی آلات بهداشتی</option>
			<option value="148">کاغذ و مقوا</option>
			<option value="138">کافی شاپ-تریا(مراکز-ملزومات)</option>
			<option value="141">کالا و تجهیزات دندانپزشکی</option>
			<option value="140">کالای خواب</option>
			<option value="86">کامپیوتر(خدمات-نرم افزار)</option>
			<option value="158">کانال سازی - نبشی سازی</option>
			<option value="146">کتابفروشی</option>
			<option value="145">کفاشی(تعمیرات)</option>
			<option value="233">کفاشی(ماشین آلات )</option>
			<option value="235">کفاشی(مواد اولیه )</option>
			<option value="142">کلید سازی</option>
			<option value="143">کمپرسورهای صنعتی-معدنی</option>
			<option value="147">کولر -شومینه</option>
			<option value="144">کیف و کفش(فروش)</option>';
			
			$result = explode('</option>',$test);
			
			foreach($result as $one){
				
				$two = str_replace('<option value="','',$one);
				$two = str_replace('">','',$two);
				$two = trim(str_replace(range(0,9),'',$two));
				
				//$query = "INSERT INTO category (`id`,`name`) VALUES ('','$two') ; ";
				//mysqli_query($connection,$query);
				}
     ?>